/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SeasonManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivate"
      | "enroll"
      | "entryFee"
      | "paymentHub"
      | "squads"
      | "updateEntryFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SquadDeactivated" | "SquadEnrolled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "enroll", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "entryFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentHub",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "squads", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "updateEntryFee",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deactivate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enroll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entryFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paymentHub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "squads", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateEntryFee",
    data: BytesLike
  ): Result;
}

export namespace SquadDeactivatedEvent {
  export type InputTuple = [squad: AddressLike];
  export type OutputTuple = [squad: string];
  export interface OutputObject {
    squad: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SquadEnrolledEvent {
  export type InputTuple = [squad: AddressLike, agentWallet: AddressLike];
  export type OutputTuple = [squad: string, agentWallet: string];
  export interface OutputObject {
    squad: string;
    agentWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SeasonManager extends BaseContract {
  connect(runner?: ContractRunner | null): SeasonManager;
  waitForDeployment(): Promise<this>;

  interface: SeasonManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivate: TypedContractMethod<[], [void], "nonpayable">;

  enroll: TypedContractMethod<[agentWallet: AddressLike], [void], "nonpayable">;

  entryFee: TypedContractMethod<[], [bigint], "view">;

  paymentHub: TypedContractMethod<[], [string], "view">;

  squads: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean] & {
        owner: string;
        agentWallet: string;
        active: boolean;
      }
    ],
    "view"
  >;

  updateEntryFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enroll"
  ): TypedContractMethod<[agentWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entryFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "paymentHub"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "squads"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean] & {
        owner: string;
        agentWallet: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateEntryFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "SquadDeactivated"
  ): TypedContractEvent<
    SquadDeactivatedEvent.InputTuple,
    SquadDeactivatedEvent.OutputTuple,
    SquadDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "SquadEnrolled"
  ): TypedContractEvent<
    SquadEnrolledEvent.InputTuple,
    SquadEnrolledEvent.OutputTuple,
    SquadEnrolledEvent.OutputObject
  >;

  filters: {
    "SquadDeactivated(address)": TypedContractEvent<
      SquadDeactivatedEvent.InputTuple,
      SquadDeactivatedEvent.OutputTuple,
      SquadDeactivatedEvent.OutputObject
    >;
    SquadDeactivated: TypedContractEvent<
      SquadDeactivatedEvent.InputTuple,
      SquadDeactivatedEvent.OutputTuple,
      SquadDeactivatedEvent.OutputObject
    >;

    "SquadEnrolled(address,address)": TypedContractEvent<
      SquadEnrolledEvent.InputTuple,
      SquadEnrolledEvent.OutputTuple,
      SquadEnrolledEvent.OutputObject
    >;
    SquadEnrolled: TypedContractEvent<
      SquadEnrolledEvent.InputTuple,
      SquadEnrolledEvent.OutputTuple,
      SquadEnrolledEvent.OutputObject
    >;
  };
}
