/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface X402MockInterface extends Interface {
  getFunction(nameOrSignature: "pay"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Payment"): EventFragment;

  encodeFunctionData(
    functionFragment: "pay",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
}

export namespace PaymentEvent {
  export type InputTuple = [
    payer: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    memo: BytesLike
  ];
  export type OutputTuple = [
    payer: string,
    recipient: string,
    amount: bigint,
    memo: string
  ];
  export interface OutputObject {
    payer: string;
    recipient: string;
    amount: bigint;
    memo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface X402Mock extends BaseContract {
  connect(runner?: ContractRunner | null): X402Mock;
  waitForDeployment(): Promise<this>;

  interface: X402MockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  pay: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, memo: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, memo: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Payment"
  ): TypedContractEvent<
    PaymentEvent.InputTuple,
    PaymentEvent.OutputTuple,
    PaymentEvent.OutputObject
  >;

  filters: {
    "Payment(address,address,uint256,bytes)": TypedContractEvent<
      PaymentEvent.InputTuple,
      PaymentEvent.OutputTuple,
      PaymentEvent.OutputObject
    >;
    Payment: TypedContractEvent<
      PaymentEvent.InputTuple,
      PaymentEvent.OutputTuple,
      PaymentEvent.OutputObject
    >;
  };
}
