/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IX402, IX402Interface } from "../../SeasonManager.sol/IX402";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "memo",
        type: "bytes",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IX402__factory {
  static readonly abi = _abi;
  static createInterface(): IX402Interface {
    return new Interface(_abi) as IX402Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IX402 {
    return new Contract(address, _abi, runner) as unknown as IX402;
  }
}
