/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DecisionLog {
  export type RecordStruct = {
    squad: AddressLike;
    decisionHash: BytesLike;
    timestamp: BigNumberish;
    metadata: string;
  };

  export type RecordStructOutput = [
    squad: string,
    decisionHash: string,
    timestamp: bigint,
    metadata: string
  ] & {
    squad: string;
    decisionHash: string;
    timestamp: bigint;
    metadata: string;
  };
}

export interface DecisionLogInterface extends Interface {
  getFunction(
    nameOrSignature: "getRecord" | "recordCount" | "recordDecision" | "records"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DecisionRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordDecision",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
}

export namespace DecisionRecordedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    squad: AddressLike,
    decisionHash: BytesLike,
    metadata: string
  ];
  export type OutputTuple = [
    recordId: bigint,
    squad: string,
    decisionHash: string,
    metadata: string
  ];
  export interface OutputObject {
    recordId: bigint;
    squad: string;
    decisionHash: string;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DecisionLog extends BaseContract {
  connect(runner?: ContractRunner | null): DecisionLog;
  waitForDeployment(): Promise<this>;

  interface: DecisionLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRecord: TypedContractMethod<
    [recordId: BigNumberish],
    [DecisionLog.RecordStructOutput],
    "view"
  >;

  recordCount: TypedContractMethod<[], [bigint], "view">;

  recordDecision: TypedContractMethod<
    [decisionHash: BytesLike, metadata: string],
    [bigint],
    "nonpayable"
  >;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        squad: string;
        decisionHash: string;
        timestamp: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [DecisionLog.RecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordDecision"
  ): TypedContractMethod<
    [decisionHash: BytesLike, metadata: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        squad: string;
        decisionHash: string;
        timestamp: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DecisionRecorded"
  ): TypedContractEvent<
    DecisionRecordedEvent.InputTuple,
    DecisionRecordedEvent.OutputTuple,
    DecisionRecordedEvent.OutputObject
  >;

  filters: {
    "DecisionRecorded(uint256,address,bytes32,string)": TypedContractEvent<
      DecisionRecordedEvent.InputTuple,
      DecisionRecordedEvent.OutputTuple,
      DecisionRecordedEvent.OutputObject
    >;
    DecisionRecorded: TypedContractEvent<
      DecisionRecordedEvent.InputTuple,
      DecisionRecordedEvent.OutputTuple,
      DecisionRecordedEvent.OutputObject
    >;
  };
}
