/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DecisionLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decisions"
      | "getDecision"
      | "getDecisionCount"
      | "logDecision"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DecisionRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "decisions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecision",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecisionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "logDecision",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "decisions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecisionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logDecision",
    data: BytesLike
  ): Result;
}

export namespace DecisionRecordedEvent {
  export type InputTuple = [
    squadId: string,
    agentChain: string,
    rationale: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    squadId: string,
    agentChain: string,
    rationale: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    squadId: string;
    agentChain: string;
    rationale: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DecisionLog extends BaseContract {
  connect(runner?: ContractRunner | null): DecisionLog;
  waitForDeployment(): Promise<this>;

  interface: DecisionLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decisions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        squadId: string;
        agentChain: string;
        rationale: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getDecision: TypedContractMethod<
    [index: BigNumberish],
    [[string, string, string, bigint]],
    "view"
  >;

  getDecisionCount: TypedContractMethod<[], [bigint], "view">;

  logDecision: TypedContractMethod<
    [squadId: string, agentChain: string, rationale: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decisions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        squadId: string;
        agentChain: string;
        rationale: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDecision"
  ): TypedContractMethod<
    [index: BigNumberish],
    [[string, string, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDecisionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "logDecision"
  ): TypedContractMethod<
    [squadId: string, agentChain: string, rationale: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DecisionRecorded"
  ): TypedContractEvent<
    DecisionRecordedEvent.InputTuple,
    DecisionRecordedEvent.OutputTuple,
    DecisionRecordedEvent.OutputObject
  >;

  filters: {
    "DecisionRecorded(string,string,string,uint256)": TypedContractEvent<
      DecisionRecordedEvent.InputTuple,
      DecisionRecordedEvent.OutputTuple,
      DecisionRecordedEvent.OutputObject
    >;
    DecisionRecorded: TypedContractEvent<
      DecisionRecordedEvent.InputTuple,
      DecisionRecordedEvent.OutputTuple,
      DecisionRecordedEvent.OutputObject
    >;
  };
}
