/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DecisionLog",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DecisionLog__factory>;
    getContractFactory(
      name: "X402Mock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.X402Mock__factory>;
    getContractFactory(
      name: "IX402",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IX402__factory>;
    getContractFactory(
      name: "SeasonManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SeasonManager__factory>;

    getContractAt(
      name: "DecisionLog",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DecisionLog>;
    getContractAt(
      name: "X402Mock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.X402Mock>;
    getContractAt(
      name: "IX402",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IX402>;
    getContractAt(
      name: "SeasonManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SeasonManager>;

    deployContract(
      name: "DecisionLog",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecisionLog>;
    deployContract(
      name: "X402Mock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.X402Mock>;
    deployContract(
      name: "IX402",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IX402>;
    deployContract(
      name: "SeasonManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SeasonManager>;

    deployContract(
      name: "DecisionLog",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecisionLog>;
    deployContract(
      name: "X402Mock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.X402Mock>;
    deployContract(
      name: "IX402",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IX402>;
    deployContract(
      name: "SeasonManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SeasonManager>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
