/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SeasonManagerV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeSquad"
      | "deactivate"
      | "enroll"
      | "entryFee"
      | "owner"
      | "seasonId"
      | "squads"
      | "updateEntryFee"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntryFeePaid"
      | "EntryFeeUpdated"
      | "SquadClosed"
      | "SquadDeactivated"
      | "SquadEnrolled"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closeSquad",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "enroll", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "entryFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "seasonId", values?: undefined): string;
  encodeFunctionData(functionFragment: "squads", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "updateEntryFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "closeSquad", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deactivate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enroll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entryFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "seasonId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "squads", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateEntryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace EntryFeePaidEvent {
  export type InputTuple = [
    payer: AddressLike,
    amount: BigNumberish,
    seasonId: string
  ];
  export type OutputTuple = [payer: string, amount: bigint, seasonId: string];
  export interface OutputObject {
    payer: string;
    amount: bigint;
    seasonId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntryFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SquadClosedEvent {
  export type InputTuple = [squadOwner: AddressLike];
  export type OutputTuple = [squadOwner: string];
  export interface OutputObject {
    squadOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SquadDeactivatedEvent {
  export type InputTuple = [squadOwner: AddressLike];
  export type OutputTuple = [squadOwner: string];
  export interface OutputObject {
    squadOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SquadEnrolledEvent {
  export type InputTuple = [
    squadOwner: AddressLike,
    agentWallet: AddressLike,
    amount: BigNumberish,
    seasonId: string
  ];
  export type OutputTuple = [
    squadOwner: string,
    agentWallet: string,
    amount: bigint,
    seasonId: string
  ];
  export interface OutputObject {
    squadOwner: string;
    agentWallet: string;
    amount: bigint;
    seasonId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SeasonManagerV2 extends BaseContract {
  connect(runner?: ContractRunner | null): SeasonManagerV2;
  waitForDeployment(): Promise<this>;

  interface: SeasonManagerV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeSquad: TypedContractMethod<[], [void], "nonpayable">;

  deactivate: TypedContractMethod<[], [void], "nonpayable">;

  enroll: TypedContractMethod<[agentWallet: AddressLike], [void], "payable">;

  entryFee: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  seasonId: TypedContractMethod<[], [string], "view">;

  squads: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint, bigint] & {
        owner: string;
        agentWallet: string;
        active: boolean;
        entryFeePaid: bigint;
        enrolledAt: bigint;
      }
    ],
    "view"
  >;

  updateEntryFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeSquad"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enroll"
  ): TypedContractMethod<[agentWallet: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "entryFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "seasonId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "squads"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint, bigint] & {
        owner: string;
        agentWallet: string;
        active: boolean;
        entryFeePaid: bigint;
        enrolledAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateEntryFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EntryFeePaid"
  ): TypedContractEvent<
    EntryFeePaidEvent.InputTuple,
    EntryFeePaidEvent.OutputTuple,
    EntryFeePaidEvent.OutputObject
  >;
  getEvent(
    key: "EntryFeeUpdated"
  ): TypedContractEvent<
    EntryFeeUpdatedEvent.InputTuple,
    EntryFeeUpdatedEvent.OutputTuple,
    EntryFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SquadClosed"
  ): TypedContractEvent<
    SquadClosedEvent.InputTuple,
    SquadClosedEvent.OutputTuple,
    SquadClosedEvent.OutputObject
  >;
  getEvent(
    key: "SquadDeactivated"
  ): TypedContractEvent<
    SquadDeactivatedEvent.InputTuple,
    SquadDeactivatedEvent.OutputTuple,
    SquadDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "SquadEnrolled"
  ): TypedContractEvent<
    SquadEnrolledEvent.InputTuple,
    SquadEnrolledEvent.OutputTuple,
    SquadEnrolledEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "EntryFeePaid(address,uint256,string)": TypedContractEvent<
      EntryFeePaidEvent.InputTuple,
      EntryFeePaidEvent.OutputTuple,
      EntryFeePaidEvent.OutputObject
    >;
    EntryFeePaid: TypedContractEvent<
      EntryFeePaidEvent.InputTuple,
      EntryFeePaidEvent.OutputTuple,
      EntryFeePaidEvent.OutputObject
    >;

    "EntryFeeUpdated(uint256)": TypedContractEvent<
      EntryFeeUpdatedEvent.InputTuple,
      EntryFeeUpdatedEvent.OutputTuple,
      EntryFeeUpdatedEvent.OutputObject
    >;
    EntryFeeUpdated: TypedContractEvent<
      EntryFeeUpdatedEvent.InputTuple,
      EntryFeeUpdatedEvent.OutputTuple,
      EntryFeeUpdatedEvent.OutputObject
    >;

    "SquadClosed(address)": TypedContractEvent<
      SquadClosedEvent.InputTuple,
      SquadClosedEvent.OutputTuple,
      SquadClosedEvent.OutputObject
    >;
    SquadClosed: TypedContractEvent<
      SquadClosedEvent.InputTuple,
      SquadClosedEvent.OutputTuple,
      SquadClosedEvent.OutputObject
    >;

    "SquadDeactivated(address)": TypedContractEvent<
      SquadDeactivatedEvent.InputTuple,
      SquadDeactivatedEvent.OutputTuple,
      SquadDeactivatedEvent.OutputObject
    >;
    SquadDeactivated: TypedContractEvent<
      SquadDeactivatedEvent.InputTuple,
      SquadDeactivatedEvent.OutputTuple,
      SquadDeactivatedEvent.OutputObject
    >;

    "SquadEnrolled(address,address,uint256,string)": TypedContractEvent<
      SquadEnrolledEvent.InputTuple,
      SquadEnrolledEvent.OutputTuple,
      SquadEnrolledEvent.OutputObject
    >;
    SquadEnrolled: TypedContractEvent<
      SquadEnrolledEvent.InputTuple,
      SquadEnrolledEvent.OutputTuple,
      SquadEnrolledEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
