/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StrategyLicenseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyLicense"
      | "grantLicense"
      | "isLicensed"
      | "owner"
      | "priceWei"
      | "revokeLicense"
      | "setPrice"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LicenseGranted"
      | "LicensePurchased"
      | "LicenseRevoked"
      | "OwnershipTransferred"
      | "PriceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyLicense",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantLicense",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isLicensed",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "priceWei", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeLicense",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyLicense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isLicensed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceWei", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace LicenseGrantedEvent {
  export type InputTuple = [buyer: AddressLike, squadId: BytesLike];
  export type OutputTuple = [buyer: string, squadId: string];
  export interface OutputObject {
    buyer: string;
    squadId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicensePurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    squadId: BytesLike,
    priceWei: BigNumberish
  ];
  export type OutputTuple = [buyer: string, squadId: string, priceWei: bigint];
  export interface OutputObject {
    buyer: string;
    squadId: string;
    priceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseRevokedEvent {
  export type InputTuple = [buyer: AddressLike, squadId: BytesLike];
  export type OutputTuple = [buyer: string, squadId: string];
  export interface OutputObject {
    buyer: string;
    squadId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [newPriceWei: BigNumberish];
  export type OutputTuple = [newPriceWei: bigint];
  export interface OutputObject {
    newPriceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrategyLicense extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyLicense;
  waitForDeployment(): Promise<this>;

  interface: StrategyLicenseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyLicense: TypedContractMethod<[squadId: BytesLike], [void], "payable">;

  grantLicense: TypedContractMethod<
    [user: AddressLike, squadId: BytesLike],
    [void],
    "nonpayable"
  >;

  isLicensed: TypedContractMethod<
    [caller: AddressLike, squadId: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  priceWei: TypedContractMethod<[], [bigint], "view">;

  revokeLicense: TypedContractMethod<
    [user: AddressLike, squadId: BytesLike],
    [void],
    "nonpayable"
  >;

  setPrice: TypedContractMethod<
    [newPriceWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyLicense"
  ): TypedContractMethod<[squadId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "grantLicense"
  ): TypedContractMethod<
    [user: AddressLike, squadId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isLicensed"
  ): TypedContractMethod<
    [caller: AddressLike, squadId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceWei"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeLicense"
  ): TypedContractMethod<
    [user: AddressLike, squadId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<[newPriceWei: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "LicenseGranted"
  ): TypedContractEvent<
    LicenseGrantedEvent.InputTuple,
    LicenseGrantedEvent.OutputTuple,
    LicenseGrantedEvent.OutputObject
  >;
  getEvent(
    key: "LicensePurchased"
  ): TypedContractEvent<
    LicensePurchasedEvent.InputTuple,
    LicensePurchasedEvent.OutputTuple,
    LicensePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "LicenseRevoked"
  ): TypedContractEvent<
    LicenseRevokedEvent.InputTuple,
    LicenseRevokedEvent.OutputTuple,
    LicenseRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;

  filters: {
    "LicenseGranted(address,bytes32)": TypedContractEvent<
      LicenseGrantedEvent.InputTuple,
      LicenseGrantedEvent.OutputTuple,
      LicenseGrantedEvent.OutputObject
    >;
    LicenseGranted: TypedContractEvent<
      LicenseGrantedEvent.InputTuple,
      LicenseGrantedEvent.OutputTuple,
      LicenseGrantedEvent.OutputObject
    >;

    "LicensePurchased(address,bytes32,uint256)": TypedContractEvent<
      LicensePurchasedEvent.InputTuple,
      LicensePurchasedEvent.OutputTuple,
      LicensePurchasedEvent.OutputObject
    >;
    LicensePurchased: TypedContractEvent<
      LicensePurchasedEvent.InputTuple,
      LicensePurchasedEvent.OutputTuple,
      LicensePurchasedEvent.OutputObject
    >;

    "LicenseRevoked(address,bytes32)": TypedContractEvent<
      LicenseRevokedEvent.InputTuple,
      LicenseRevokedEvent.OutputTuple,
      LicenseRevokedEvent.OutputObject
    >;
    LicenseRevoked: TypedContractEvent<
      LicenseRevokedEvent.InputTuple,
      LicenseRevokedEvent.OutputTuple,
      LicenseRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceUpdated(uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
  };
}
