/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StrategyVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "depositedAmount"
      | "getVaultStats"
      | "lastUpdated"
      | "pnlDelta"
      | "recordPnL"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VaultUpdated"): EventFragment;

  encodeFunctionData(functionFragment: "deposit", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "depositedAmount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultStats",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pnlDelta", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "recordPnL",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastUpdated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pnlDelta", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordPnL", data: BytesLike): Result;
}

export namespace VaultUpdatedEvent {
  export type InputTuple = [
    squadId: BytesLike,
    pnl: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [squadId: string, pnl: bigint, timestamp: bigint];
  export interface OutputObject {
    squadId: string;
    pnl: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrategyVault extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyVault;
  waitForDeployment(): Promise<this>;

  interface: StrategyVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<[squadId: BytesLike], [void], "payable">;

  depositedAmount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getVaultStats: TypedContractMethod<
    [squadId: BytesLike],
    [[bigint, bigint, bigint] & { deposited: bigint; pnl: bigint; ts: bigint }],
    "view"
  >;

  lastUpdated: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  pnlDelta: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  recordPnL: TypedContractMethod<
    [squadId: BytesLike, delta: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[squadId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "depositedAmount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultStats"
  ): TypedContractMethod<
    [squadId: BytesLike],
    [[bigint, bigint, bigint] & { deposited: bigint; pnl: bigint; ts: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastUpdated"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pnlDelta"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordPnL"
  ): TypedContractMethod<
    [squadId: BytesLike, delta: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "VaultUpdated"
  ): TypedContractEvent<
    VaultUpdatedEvent.InputTuple,
    VaultUpdatedEvent.OutputTuple,
    VaultUpdatedEvent.OutputObject
  >;

  filters: {
    "VaultUpdated(bytes32,int256,uint256)": TypedContractEvent<
      VaultUpdatedEvent.InputTuple,
      VaultUpdatedEvent.OutputTuple,
      VaultUpdatedEvent.OutputObject
    >;
    VaultUpdated: TypedContractEvent<
      VaultUpdatedEvent.InputTuple,
      VaultUpdatedEvent.OutputTuple,
      VaultUpdatedEvent.OutputObject
    >;
  };
}
