/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace StrategyRegistry {
  export type ListingStruct = {
    squadId: BytesLike;
    owner: AddressLike;
    name: string;
    assetPair: string;
    mode: string;
    risk: string;
    available: boolean;
    updatedAt: BigNumberish;
  };

  export type ListingStructOutput = [
    squadId: string,
    owner: string,
    name: string,
    assetPair: string,
    mode: string,
    risk: string,
    available: boolean,
    updatedAt: bigint
  ] & {
    squadId: string;
    owner: string;
    name: string;
    assetPair: string;
    mode: string;
    risk: string;
    available: boolean;
    updatedAt: bigint;
  };
}

export interface StrategyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllListings"
      | "getListing"
      | "getOwnerListings"
      | "listStrategy"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "StrategyListed"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllListings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerListings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listStrategy",
    values: [BytesLike, string, string, string, string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listStrategy",
    data: BytesLike
  ): Result;
}

export namespace StrategyListedEvent {
  export type InputTuple = [
    squadId: BytesLike,
    owner: AddressLike,
    name: string,
    available: boolean
  ];
  export type OutputTuple = [
    squadId: string,
    owner: string,
    name: string,
    available: boolean
  ];
  export interface OutputObject {
    squadId: string;
    owner: string;
    name: string;
    available: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrategyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyRegistry;
  waitForDeployment(): Promise<this>;

  interface: StrategyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllListings: TypedContractMethod<[], [string[]], "view">;

  getListing: TypedContractMethod<
    [squadId: BytesLike],
    [StrategyRegistry.ListingStructOutput],
    "view"
  >;

  getOwnerListings: TypedContractMethod<
    [owner: AddressLike],
    [string[]],
    "view"
  >;

  listStrategy: TypedContractMethod<
    [
      squadId: BytesLike,
      name: string,
      assetPair: string,
      mode: string,
      risk: string,
      available: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllListings"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [squadId: BytesLike],
    [StrategyRegistry.ListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerListings"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "listStrategy"
  ): TypedContractMethod<
    [
      squadId: BytesLike,
      name: string,
      assetPair: string,
      mode: string,
      risk: string,
      available: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "StrategyListed"
  ): TypedContractEvent<
    StrategyListedEvent.InputTuple,
    StrategyListedEvent.OutputTuple,
    StrategyListedEvent.OutputObject
  >;

  filters: {
    "StrategyListed(bytes32,address,string,bool)": TypedContractEvent<
      StrategyListedEvent.InputTuple,
      StrategyListedEvent.OutputTuple,
      StrategyListedEvent.OutputObject
    >;
    StrategyListed: TypedContractEvent<
      StrategyListedEvent.InputTuple,
      StrategyListedEvent.OutputTuple,
      StrategyListedEvent.OutputObject
    >;
  };
}
